:PROPERTIES:
:GPTEL_MODEL: gpt-4o-mini
:GPTEL_BACKEND: ChatGPT
:GPTEL_SYSTEM: You are a large language model living in Emacs and a helpful assistant. Respond concisely.
:GPTEL_BOUNDS: ((806 . 943) (944 . 960))
:header-args: :tangle ansible/tasks/install_frigate.yml
:END:


*** Create a playbook that changes the hostname to that of the inventory

Certainly! Below is an Ansible playbook that sets the hostname to that of the
inventory.

*** Playbook: =set_hostname.yml=

#+begin_src yaml 

---
- name: INSTALL FRIGATE
  hosts: all
  tasks:
    - name: set system hostname to {{ inventory_hostname }}
      become: yes
      command: hostnamectl set-hostname {{ inventory_hostname }}

#+end_src


*** Can you make a playbook that modifies /etc/sudoers to make the user "sice" run sudo without password?

Certainly! Below is an Ansible playbook that modifies the =/etc/sudoers= file to
allow the user "sice" to run =sudo= without a password.

#+begin_src yaml 
#---

    - name: Ensure user sice is in the sudo group
      become: yes
      become_method: sudo
      user:
        name: sice
        groups: sudo
        append: yes

  
    - name: Allow members of the sudo group to run sudo without a password
      become: yes
      become_method: sudo
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

#+end_src

*** Explanation:
	- *=hosts: all=*: Applies the playbook to all hosts in the inventory.
	- *=become: yes=*: Enables privilege escalation.
	- *=vars_prompt=*: Prompts the user for the sudo password.
	- *=tasks=*: Contains the tasks to be performed.
	- *=user= module*: Ensures the user =sice= is added to the =sudo= group.


*** write an ansible playbook that:
		1. copy the local file
           "/home/concesion/instalacion/DVAS/FRIGATE/FRIGATE-INSTALL.tar" into
           the directory "/home/sice/instalacion"
		2. Untar FRIGATE-INSTALL.tar in
           "//home/concesion/instalacion/DVAS/FRIGATE/"
		3. Execute "dpkg -i *" in directory
           "//home/concesion/instalacion/DVAS/FRIGATE/PODMAN-PKGS/"

Here's an Ansible playbook that accomplishes the tasks you specified:

 #+begin_src yaml 
#---

    - name: Ensure the directory ~/instalacion/FRIGATE exists
      file:
        path: ~/instalacion/DVAS/FRIGATE
        state: directory
        mode: '0755'  # Optional: Set permissions

   
    - name: Copy FRIGATE-INSTALL.tar to /home/sice/instalacion
      copy:
        src: /home/concesion/instalacion/DVAS/FRIGATE/FRIGATE-INSTALL.tar
        dest: /home/sice/instalacion/

   
    - name: Untar FRIGATE-INSTALL.tar
      unarchive:
        src: /home/sice/instalacion/FRIGATE-INSTALL.tar
        dest: /home/sice/instalacion/DVAS/FRIGATE/
        remote_src: yes
   
    - name: Untar tmux.tar
      unarchive:
        src: /home/sice/instalacion/DVAS/FRIGATE/frigate-install/tmux.tar
        dest: ~/.
        remote_src: yes

    - name: Prepare tmux
      shell: ln -sf .tmux/.tmux.conf
      args:
        chdir: ~/.
   
    - name: Load frigate_0.13.1-sice-20240628-03.bz2 podman image
      shell: bzcat frigate_0.13.1-sice-20240628-03.bz2 | podman load
      args:
        chdir: ~/instalacion/DVAS/FRIGATE/frigate-install # Change to the specified directory before executing the command

#   - name: Install all .deb packages in /path
#     become: yes
#     shell: dpkg -i *.deb
#     args:
#       chdir: /home/sice/instalacion/DVAS/FRIGATE/frigate-install/PODMAN-PKGS/
#+end_src


*** Usage:
Save this playbook in a file named =install_frigate.yml=, and execute it using:
#+begin_src bash :tangle no
  # conectarse a MOMS (172.30.30.12) como usuario concesion y hacer lo que sigue
  cd ~/instalacion/DVAS/FRIGATE/prt-frigate-ansible
  ansible-playbook ansible/tasks/install_frigate.yml -i inventory.ini -l prt-zm01
#+end_src

