---
- name: Install Frigate
  hosts: all
  tasks:

    - name: Ensure the directory exists
      file:
        path: /home/concesion/instalacion/DVAS/FRIGATE
        state: directory
        mode: '0755'  # Optional: Set permissions

    - name: Copy FRIGATE-INSTALL.tar to destination
      copy:
        src: /home/concesion/instalacion/DVAS/FRIGATE/FRIGATE-INSTALL.tar
        dest: /home/sice/instalacion/

    - name: Untar FRIGATE-INSTALL.tar
      unarchive:
        src: /home/sice/instalacion/FRIGATE-INSTALL.tar
        dest: /home/concesion/instalacion/DVAS/FRIGATE/
        remote_src: yes

    - name: Execute dpkg -i in PODMAN-PKGS directory
      command: sudo dpkg -i *
      args:
        chdir: /home/concesion/instalacion/DVAS/FRIGATE/PODMAN-PKGS/
